### PR TITLE
refactor: merge authority table creation into init migration

### PR DESCRIPTION
**Pull request by john-cremit**
# refactor: merge authority table creation into init migration

- [ ] You've included unit or integration tests for your change, where applicable.
- [ ] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

Summary of the changes (Less than 80 chars)

## Description

This pull request refactors the database migration logic by consolidating the creation of the authority table into the initial database migration script. Previously, multiple migration scripts would handle the creation of new tables, which required frequent updates if column names or table structures changed prior to release. By combining these steps into a single migration, we increase the efficiency of the migration process and simplify future maintenance.

Additionally, an unused column ('type') from the `applied_policy` table that leads to major bug on the secret creation was removed.

### CODE REVIEW

**Comment by boris-cremit** [comment]
This approach has an issue where the added migration is not applied to users who have already completed previous migrations. To continuously provide version upgrades to existing users, version-specific migrations must be maintained as before. If the reasoning is that this is acceptable since it is before the release, that’s fine, but if the suggestion is to manage it this way moving forward, it could lead to problems.

**Comment by john-cremit** [comment]
> This approach has an issue where the added migration is not applied to users who have already completed previous migrations. To continuously provide version upgrades to existing users, version-specific migrations must be maintained as before. If the reasoning is that this is acceptable since it is before the release, that’s fine, but if the suggestion is to manage it this way moving forward, it could lead to problems.

I would suggest consolidating migrations into a single file until the next release version update (e.g., x.y.z -> x.y.z+1). Here's my reasoning:  
1. For pre-release changes, managing multiple migration files to handle column modifications in certain tables is inefficient.  
2. Having separate migration files for each small schema change during development creates unnecessary complexity.  

Meanwhile, I want to emphasize that this approach should only be used during pre-release development. For production releases, we should maintain proper version-specific migrations to ensure:  

- Reliable upgrade paths for existing users  
- Proper version control of schema changes  
- Ability to roll back specific changes if needed  

Thoughts on this approach?

**Comment by boris-cremit** [comment]
> > This approach has an issue where the added migration is not applied to users who have already completed previous migrations. To continuously provide version upgrades to existing users, version-specific migrations must be maintained as before. If the reasoning is that this is acceptable since it is before the release, that’s fine, but if the suggestion is to manage it this way moving forward, it could lead to problems.
> 
> I would suggest consolidating migrations into a single file until the next release version update (e.g., x.y.z -> x.y.z+1). Here's my reasoning:
> 
> 1. For pre-release changes, managing multiple migration files to handle column modifications in certain tables is inefficient.
> 2. Having separate migration files for each small schema change during development creates unnecessary complexity.
> 
> Meanwhile, I want to emphasize that this approach should only be used during pre-release development. For production releases, we should maintain proper version-specific migrations to ensure:
> 
> * Reliable upgrade paths for existing users
> * Proper version control of schema changes
> * Ability to roll back specific changes if needed
> 
> Thoughts on this approach? @boris-cremit

That sounds reasonable. However, to preserve the atomicity and intent of each pull request, I would like to propose the following additional details:

Include the necessary migrations in each pull request to ensure functionality.
Create a release PR and consolidate the migrations added in previous PRs into a single migration within that release PR (as done in this PR).

**Comment by john-cremit** [comment]
Closed by #163

**Pull request closed without merging**
